export const PLUGIN_ID = "paperclip-token-governor";
export const PLUGIN_VERSION = "0.1.0";
export const PAGE_ROUTE = "token-governor";

export const SLOT_IDS = {
  page: "token-governor-page",
  dashboardWidget: "token-governor-dashboard-widget",
} as const;

export const EXPORT_NAMES = {
  page: "GovernorPage",
  dashboardWidget: "GovernorWidget",
} as const;

export const JOB_KEYS = {
  reconcile: "reconcile-agents",
  analyze: "analyze-efficiency",
} as const;

export const STREAM_CHANNELS = {
  wakeLog: "wake-log",
} as const;

/** State keys for plugin state store. */
export const STATE_KEYS = {
  /** List of agent IDs under management. */
  managedAgents: "managed-agents",
  /** Wake log entries. */
  wakeLog: "wake-log",
  /** Accumulated savings data. */
  savings: "savings",
  /** Recommendations generated by analysis job. */
  recommendations: "recommendations",
  /** Per-agent efficiency metrics. */
  agentMetrics: "agent-metrics",
} as const;

/** Default plugin configuration. */
export const DEFAULT_CONFIG = {
  /** Roles exempt from pause management (always run on their own schedule). */
  exemptRoles: ["ceo"] as string[],
  /** Specific agent IDs exempt from management. */
  exemptAgentIds: [] as string[],
  /**
   * Who can wake managed agents:
   *  - "chain_of_command": only the agent's manager chain up to CEO
   *  - "direct_manager": only the agent's direct reportsTo
   *  - "anyone": any actor (effectively just dormant-until-assigned)
   */
  wakePolicy: "chain_of_command" as "chain_of_command" | "direct_manager" | "anyone",
  /** Whether @mentions from any agent can wake a managed agent. */
  allowMentionWakes: true,
  /** Whether human users can always wake any managed agent. */
  allowDirectUserWakes: true,
  /** Auto-manage newly created agents. */
  autoManageNewAgents: true,
  /** Maximum wake log entries to keep. */
  maxWakeLogEntries: 200,
} as const;

export type GovernorConfig = {
  exemptRoles: string[];
  exemptAgentIds: string[];
  wakePolicy: "chain_of_command" | "direct_manager" | "anyone";
  allowMentionWakes: boolean;
  allowDirectUserWakes: boolean;
  autoManageNewAgents: boolean;
  maxWakeLogEntries: number;
};
