/** An agent record as returned by ctx.agents.list(). */
export interface AgentRecord {
  id: string;
  companyId: string;
  name: string;
  role: string | null;
  status: string;
  reportsTo: string | null;
  budgetMonthlyCents: number | null;
  spentMonthlyCents: number | null;
  lastHeartbeatAt: string | null;
  runtimeConfig: Record<string, unknown> | null;
  adapterType: string | null;
  createdAt: string;
  updatedAt: string;
}

/** A wake log entry persisted in plugin state. */
export interface WakeLogEntry {
  id: string;
  timestamp: string;
  agentId: string;
  agentName: string;
  action: "approved" | "rejected" | "completed" | "auto_paused" | "auto_resumed" | "reconciled";
  reason: string;
  actorId: string | null;
  actorType: "agent" | "user" | "system";
  issueId: string | null;
  costCents: number | null;
  tokenCount: number | null;
  durationMs: number | null;
}

/** Per-agent efficiency metrics computed by the analysis job. */
export interface AgentMetrics {
  agentId: string;
  agentName: string;
  role: string | null;
  status: string;
  managed: boolean;
  /** Total runs in the analysis window. */
  totalRuns: number;
  /** Runs that had a real assignment or mention trigger. */
  usefulRuns: number;
  /** Total spend in cents during the window. */
  spendCents: number;
  /** Budget in cents (null = no budget). */
  budgetCents: number | null;
  /** Ratio of cached input tokens to total input tokens (0-1). */
  cacheHitRatio: number | null;
  /** How often sessions were reused vs fresh. */
  sessionReuseRatio: number | null;
  /** Estimated wasted spend from timer heartbeats with no work (cents). */
  wastedTimerSpendCents: number;
  /** Last run timestamp. */
  lastRunAt: string | null;
  /** Computed at timestamp. */
  computedAt: string;
}

/** A recommendation generated by the analysis engine. */
export interface Recommendation {
  id: string;
  agentId: string;
  agentName: string;
  type:
    | "enable_governor"
    | "disable_timer"
    | "set_budget"
    | "lower_concurrency"
    | "stale_agent"
    | "no_budget"
    | "high_burn_rate";
  severity: "info" | "warning" | "critical";
  title: string;
  description: string;
  estimatedSavingsCents: number;
  /** Whether the plugin can auto-apply this action. */
  autoApplicable: boolean;
  createdAt: string;
  dismissedAt: string | null;
}

/** Savings summary persisted in plugin state. */
export interface SavingsData {
  /** Total wakeups prevented by the gatekeeper. */
  preventedWakeups: number;
  /** Estimated cost savings in cents. */
  estimatedSavingsCents: number;
  /** Wakeups that were rejected due to policy. */
  rejectedWakeups: number;
  /** Runs completed under governor management. */
  completedRuns: number;
  /** Window start for the current tracking period. */
  periodStart: string;
  /** Last updated timestamp. */
  updatedAt: string;
}
